window.App = {
    user: null,
    session: null,
    state: {
        history: [],
        characters: [],
        activeCharacter: null
    },
    currentConversationId: null,
    isAutoScrolling: true,
    controller: null,
    attachedImageBase64: null,
    newCharAvatarBase64: null,
    editingCharId: null,
    DEFAULT_AI_AVATAR: 'https://api.dicebear.com/7.x/bottts/svg?seed=Ruby',
    DEFAULT_USER_AVATAR: 'https://api.dicebear.com/7.x/avataaars/svg?seed=User',
    currentMode: 'chat',
    settingsData: null,
    UI: {}
};

document.addEventListener("DOMContentLoaded", () => {
    window.App.UI = {
        chatLog: document.getElementById('chat-log'),
        prompt: document.getElementById('prompt'),
        sendBtn: document.getElementById('send-btn'),
        stopBtn: document.getElementById('stop-btn'),
        newChatBtn: document.getElementById('new-chat-btn'),
        charsBtn: document.getElementById('chars-btn'),
        sidebar: document.getElementById('sidebar'),
        overlay: document.getElementById('overlay'),
        menuBtn: document.getElementById('menu-btn'),
        conversationsList: document.getElementById('conversations-list'),
        chatSearch: document.getElementById('chat-search'),
        profileBtn: document.getElementById('profile-btn'),
        profileModal: document.getElementById('profile-modal'),
        closeProfileModal: document.getElementById('close-profile-modal'),
        apiKey: document.getElementById('api-key'),
        sysPrompt: document.getElementById('system-prompt'),
        narrativePrompt: document.getElementById('narrative-prompt'),
        tempSlider: document.getElementById('temperature'),
        tempVal: document.getElementById('temp-val'),
        ctxSlider: document.getElementById('context-limit'),
        ctxVal: document.getElementById('ctx-val'),
        maxTokensSlider: document.getElementById('max-tokens'),
        maxTokensVal: document.getElementById('max-tokens-val'),
        model: document.getElementById('model-select'),
        charModal: document.getElementById('char-modal'),
        closeCharModal: document.getElementById('close-char-modal'),
        charList: document.getElementById('char-list'),
        newCharName: document.getElementById('new-char-name'),
        newCharAvatarBtn: document.getElementById('new-char-avatar-btn'),
        newCharAvatarFile: document.getElementById('new-char-avatar-file'),
        newCharAvatarPreview: document.getElementById('new-char-avatar-preview'),
        newCharPrompt: document.getElementById('new-char-prompt'),
        saveCharBtn: document.getElementById('save-char-btn'),
        cancelEditCharBtn: document.getElementById('cancel-edit-char-btn'),
        clearCharBtn: document.getElementById('clear-char-btn'),
        activeCharDisplay: document.getElementById('active-char-display'),
        activeCharImg: document.getElementById('active-char-img'),
        activeCharName: document.getElementById('active-char-name'),
        attachImgBtn: document.getElementById('attach-img-btn'),
        imageUpload: document.getElementById('image-upload'),
        imagePreviewContainer: document.getElementById('image-preview-container'),
        imagePreview: document.getElementById('image-preview'),
        clearImgBtn: document.getElementById('clear-img-btn'),
        tokenCounter: document.getElementById('token-counter'),
        persistMem: document.getElementById('persist-mem'),
        micBtn: document.getElementById('mic-btn'),
        voiceSheet: document.getElementById('voice-sheet'),
        voiceCancelBtn: document.getElementById('voice-cancel-btn'),
        voiceMode: document.getElementById('voice-mode-select'),
        googleTtsKey: document.getElementById('google-tts-key'),
        googleVoiceSelect: document.getElementById('google-voice-select'),
        exportBtn: document.getElementById('export-btn'),
        mobileSidebarClose: document.getElementById('mobile-sidebar-close'),
        architectBtn: document.getElementById('architect-btn'),
        architectModal: document.getElementById('architect-modal'),
        closeArchitectModal: document.getElementById('close-architect-modal'),
        architectPrompt: document.getElementById('architect-prompt'),
        architectBuildBtn: document.getElementById('architect-build-btn'),
        architectLoading: document.getElementById('architect-loading')
    };
});
